spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          facebook:
#            clientId: 747661655907203
#            clientSecret: a6851772baeffd06c5e8f2c743030f3e
#            scope: email, public_profile
  thymeleaf:
    cache: false
  artemis:
    host: localhost
    port: 61616
    user: admin
    password: admin
  jms:
    template:
      default-destination:
        tacocloud.order.queue
  datasource:
    generate-unique-name: false
    name: tacocloud
    url: jdbc:h2:mem:tacocloud
    username: admin
    password: admin

taco:
  orders:
    pageSize: 10 #export TACO_ORDERS_PAGESIZE=10

