spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          facebook:
#            clientId: 747661655907203
#            clientSecret: a6851772baeffd06c5e8f2c743030f3e
#            scope: email, public_profile

  rsocket:
    server:
      transport: websocket
      mapping-path: /rsocket
      port: 7000
  thymeleaf:
    cache: false
  kafka:
    template:
      default-topic: tacocloud.orders.topic
    bootstrap-servers:
      - localhost:9092
  datasource:
    generate-unique-name: false
    name: tacocloud
    url: jdbc:h2:mem:tacocloud
    username: admin
    password: admin

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
taco:
  orders:
    pageSize: 10 #export TACO_ORDERS_PAGESIZE=10

info:
  email: fabricio.jacob@outlook.com
