version: "3"
services:
  artemis:
    environment:
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: admin
    image: vromero/activemq-artemis
    ports:
      - 61616:61616
      - 8161:8161
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672  