version: "3"
services:
  artemis:
    environment:
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: admin
    image: vromero/activemq-artemis
    ports:
      - 61616:61616
      - 8161:8161

  zookeeper:
    container_name: zookeeper_container
    image: debezium/zookeeper:1.1
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    networks:
      - backend

  kafka:
    container_name: kafka_container
    image: debezium/kafka:1.1
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      - backend
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
networks:
  backend:
    driver: bridge        