version: "3"
services:
  cassandra:
    image: cassandra:3.11.2
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - "./cassandra_local:/var/lib/cassandra"
      - "./cassandra_local/cassandra_init.sh:/cassandra_init.sh"
    command: "sh /cassandra_init.sh"